# Generated by Django 4.2.3 on 2023-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_nft_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
