# Generated by Django 4.2.3 on 2023-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_nft_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='nft_file',
        ),
        migrations.RemoveField(
            model_name='ownednfts',
            name='image',
        ),
        migrations.AddField(
            model_name='ownednfts',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mintingpayment',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs'),
        ),
        migrations.AlterField(
            model_name='verficationfee',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs'),
        ),
    ]
