# Generated by Django 4.2.3 on 2023-11-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_nft_nft_file_remove_ownednfts_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='nft_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proof'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
