# Generated by Django 4.2.3 on 2023-07-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_nft_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
