# Generated by Django 4.2.3 on 2023-07-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_nft_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
