# Generated by Django 4.2.3 on 2024-08-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_marketplace_nft_image_alter_sale_payment_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='image_url',
        ),
        migrations.AddField(
            model_name='nft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nfts'),
        ),
        migrations.AlterField(
            model_name='ownednfts',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='owned-nft'),
        ),
    ]
