# Generated by Django 4.2.3 on 2025-04-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_nft_image_url_nft_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownednfts',
            old_name='image_url',
            new_name='image',
        ),
    ]
