# Generated by Django 4.2.3 on 2025-12-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_image_url_ownednfts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
