# Generated by Django 4.2.3 on 2023-07-28 23:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_nft_description_nft_on_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='image',
        ),
        migrations.AddField(
            model_name='nft',
            name='nft_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
