# Generated by Django 4.2.3 on 2025-12-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_nft_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='nft_image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace'),
        ),
    ]
