# Generated by Django 4.2.3 on 2023-07-29 20:14

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_nft_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='MintingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('proof', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mint_payment', to='accounts.nft')),
            ],
        ),
    ]
