# Generated by Django 4.2.3 on 2023-07-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_nft_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='amount_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
