# Generated by Django 4.2.3 on 2023-07-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_nft_amount_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='amount_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
