# Generated by Django 4.2.3 on 2023-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_nft_amount_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=4, null=True),
        ),
    ]
