# Generated by Django 4.2.3 on 2023-08-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
