# Generated by Django 4.2.3 on 2023-08-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_history_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mintingpayment',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
