# Generated by Django 4.2.3 on 2023-08-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_nft_nft_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
