# Generated by Django 4.2.3 on 2023-08-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='price_sold',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
