# Generated by Django 4.2.3 on 2023-08-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_nft_price_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_own',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
