# Generated by Django 4.2.3 on 2023-08-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_ownednfts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='price_sold',
        ),
    ]
